import { render, screen, fireEvent } from "@testing-library/react";
import { PDFSelectionLayer } from "../pdf-selection-layer";
import { usePDFStore } from "@/lib/pdf-store";

jest.mock("@/lib/pdf-store");

describe("PDFSelectionLayer", () => {
  const mockStore = {
    isSelectionMode: true,
    toggleSelectionMode: jest.fn(),
  };

  beforeEach(() => {
    jest.clearAllMocks();
    (usePDFStore as unknown as jest.Mock).mockReturnValue(mockStore);
  });

  it("renders when selection mode is active", () => {
    const { container } = render(
      <PDFSelectionLayer
        page={{} as any}
        scale={1}
        rotation={0}
        pageNumber={1}
      />
    );
    
    expect(container.firstChild).not.toBeNull();
  });

  it("does not render when selection mode is inactive", () => {
    (usePDFStore as unknown as jest.Mock).mockReturnValue({
      ...mockStore,
      isSelectionMode: false,
    });

    const { container } = render(
      <PDFSelectionLayer
        page={{} as any}
        scale={1}
        rotation={0}
        pageNumber={1}
      />
    );
    
    expect(container.firstChild).toBeNull();
  });

  it("starts selection on mouse down", () => {
    const { container } = render(
      <PDFSelectionLayer
        page={{} as any}
        scale={1}
        rotation={0}
        pageNumber={1}
      />
    );

    const layer = container.firstChild as Element;
    fireEvent.mouseDown(layer, { clientX: 0, clientY: 0 });
    fireEvent.mouseMove(layer, { clientX: 100, clientY: 100 });
    
    // After move, we expect a selection box.
    // The component logic creates a box if selection exists.
    // We can't easily assert internal state, but we can check for the box element render.
    
    // Wait, `handleMouseMove` updates state which causes re-render.
    // The selection box has class "absolute border-2 border-primary bg-primary/20"
    
    // Since we can't rely on class names if they change or are generated by tailwind-merge strictly,
    // we can look for the style.
    
    // Or better, we can check if the selection-menu appears after mouse up?
    fireEvent.mouseUp(layer);
    
    // Menu has buttons Copy, Save Image, etc.
    expect(screen.getByTitle("Copy Image")).toBeInTheDocument();
  });
});
