/**
 * Emoji shortcode mapping
 * Supports GitHub-style emoji shortcodes like :smile: :heart: etc.
 */

export const emojiMap: Record<string, string> = {
  // Smileys & Emotion
  smile: "😄",
  laughing: "😆",
  blush: "😊",
  smiley: "😃",
  relaxed: "☺️",
  smirk: "😏",
  heart_eyes: "😍",
  kissing_heart: "😘",
  kissing_closed_eyes: "😚",
  flushed: "😳",
  relieved: "😌",
  satisfied: "😆",
  grin: "😁",
  wink: "😉",
  stuck_out_tongue_winking_eye: "😜",
  stuck_out_tongue_closed_eyes: "😝",
  grinning: "😀",
  kissing: "😗",
  kissing_smiling_eyes: "😙",
  stuck_out_tongue: "😛",
  sleeping: "😴",
  worried: "😟",
  frowning: "😦",
  anguished: "😧",
  open_mouth: "😮",
  grimacing: "😬",
  confused: "😕",
  hushed: "😯",
  expressionless: "😑",
  unamused: "😒",
  sweat_smile: "😅",
  sweat: "😓",
  disappointed_relieved: "😥",
  weary: "😩",
  pensive: "😔",
  disappointed: "😞",
  confounded: "😖",
  fearful: "😨",
  cold_sweat: "😰",
  persevere: "😣",
  cry: "😢",
  sob: "😭",
  joy: "😂",
  astonished: "😲",
  scream: "😱",
  tired_face: "😫",
  angry: "😠",
  rage: "😡",
  triumph: "😤",
  sleepy: "😪",
  yum: "😋",
  mask: "😷",
  sunglasses: "😎",
  dizzy_face: "😵",
  imp: "👿",
  smiling_imp: "😈",
  neutral_face: "😐",
  no_mouth: "😶",
  innocent: "😇",
  alien: "👽",
  yellow_heart: "💛",
  blue_heart: "💙",
  purple_heart: "💜",
  heart: "❤️",
  green_heart: "💚",
  broken_heart: "💔",
  heartbeat: "💓",
  heartpulse: "💗",
  two_hearts: "💕",
  revolving_hearts: "💞",
  cupid: "💘",
  sparkling_heart: "💖",
  sparkles: "✨",
  star: "⭐",
  star2: "🌟",
  dizzy: "💫",
  boom: "💥",
  collision: "💥",
  anger: "💢",
  exclamation: "❗",
  question: "❓",
  grey_exclamation: "❕",
  grey_question: "❔",
  zzz: "💤",
  dash: "💨",
  sweat_drops: "💦",
  notes: "🎶",
  musical_note: "🎵",
  fire: "🔥",
  hankey: "💩",
  poop: "💩",
  shit: "💩",
  "+1": "👍",
  thumbsup: "👍",
  "-1": "👎",
  thumbsdown: "👎",
  ok_hand: "👌",
  punch: "👊",
  facepunch: "👊",
  fist: "✊",
  v: "✌️",
  wave: "👋",
  hand: "✋",
  raised_hand: "✋",
  open_hands: "👐",
  point_up: "☝️",
  point_down: "👇",
  point_left: "👈",
  point_right: "👉",
  raised_hands: "🙌",
  pray: "🙏",
  point_up_2: "👆",
  clap: "👏",
  muscle: "💪",
  metal: "🤘",
  fu: "🖕",
  walking: "🚶",
  runner: "🏃",
  running: "🏃",
  couple: "👫",
  family: "👪",
  two_men_holding_hands: "👬",
  two_women_holding_hands: "👭",
  dancer: "💃",
  dancers: "👯",
  ok_woman: "🙆",
  no_good: "🙅",
  information_desk_person: "💁",
  raising_hand: "🙋",
  bride_with_veil: "👰",
  bow: "🙇",
  couplekiss: "💏",
  couple_with_heart: "💑",
  massage: "💆",
  haircut: "💇",
  nail_care: "💅",
  boy: "👦",
  girl: "👧",
  woman: "👩",
  man: "👨",
  baby: "👶",
  older_woman: "👵",
  older_man: "👴",
  cop: "👮",
  angel: "👼",
  princess: "👸",
  ghost: "👻",
  skull: "💀",
  // Animals & Nature
  dog: "🐶",
  cat: "🐱",
  mouse: "🐭",
  hamster: "🐹",
  rabbit: "🐰",
  wolf: "🐺",
  frog: "🐸",
  tiger: "🐯",
  koala: "🐨",
  bear: "🐻",
  pig: "🐷",
  cow: "🐮",
  monkey: "🐵",
  horse: "🐴",
  snake: "🐍",
  bird: "🐦",
  chicken: "🐔",
  penguin: "🐧",
  bug: "🐛",
  bee: "🐝",
  ant: "🐜",
  beetle: "🐞",
  snail: "🐌",
  octopus: "🐙",
  turtle: "🐢",
  fish: "🐟",
  whale: "🐳",
  dolphin: "🐬",
  cherry_blossom: "🌸",
  tulip: "🌷",
  rose: "🌹",
  sunflower: "🌻",
  hibiscus: "🌺",
  maple_leaf: "🍁",
  leaves: "🍃",
  fallen_leaf: "🍂",
  herb: "🌿",
  mushroom: "🍄",
  cactus: "🌵",
  palm_tree: "🌴",
  evergreen_tree: "🌲",
  deciduous_tree: "🌳",
  chestnut: "🌰",
  seedling: "🌱",
  blossom: "🌼",
  ear_of_rice: "🌾",
  shell: "🐚",
  earth_africa: "🌍",
  earth_americas: "🌎",
  earth_asia: "🌏",
  full_moon: "🌕",
  new_moon: "🌑",
  moon: "🌙",
  sunny: "☀️",
  cloud: "☁️",
  umbrella: "☂️",
  snowflake: "❄️",
  snowman: "⛄",
  zap: "⚡",
  rainbow: "🌈",
  ocean: "🌊",
  // Food & Drink
  apple: "🍎",
  green_apple: "🍏",
  tangerine: "🍊",
  lemon: "🍋",
  cherries: "🍒",
  grapes: "🍇",
  watermelon: "🍉",
  strawberry: "🍓",
  peach: "🍑",
  melon: "🍈",
  banana: "🍌",
  pear: "🍐",
  pineapple: "🍍",
  sweet_potato: "🍠",
  eggplant: "🍆",
  tomato: "🍅",
  corn: "🌽",
  hamburger: "🍔",
  pizza: "🍕",
  fries: "🍟",
  poultry_leg: "🍗",
  meat_on_bone: "🍖",
  spaghetti: "🍝",
  curry: "🍛",
  fried_shrimp: "🍤",
  bento: "🍱",
  sushi: "🍣",
  rice_ball: "🍙",
  rice_cracker: "🍘",
  rice: "🍚",
  ramen: "🍜",
  stew: "🍲",
  oden: "🍢",
  dango: "🍡",
  egg: "🥚",
  bread: "🍞",
  doughnut: "🍩",
  custard: "🍮",
  icecream: "🍨",
  ice_cream: "🍦",
  shaved_ice: "🍧",
  birthday: "🎂",
  cake: "🍰",
  cookie: "🍪",
  chocolate_bar: "🍫",
  candy: "🍬",
  lollipop: "🍭",
  honey_pot: "🍯",
  beer: "🍺",
  beers: "🍻",
  wine_glass: "🍷",
  cocktail: "🍸",
  tropical_drink: "🍹",
  sake: "🍶",
  tea: "🍵",
  coffee: "☕",
  // Objects
  watch: "⌚",
  iphone: "📱",
  calling: "📲",
  computer: "💻",
  keyboard: "⌨️",
  desktop_computer: "🖥️",
  printer: "🖨️",
  mouse_three_button: "🖱️",
  trackball: "🖲️",
  cd: "💿",
  dvd: "📀",
  floppy_disk: "💾",
  camera: "📷",
  video_camera: "📹",
  movie_camera: "🎥",
  tv: "📺",
  radio: "📻",
  telephone: "☎️",
  telephone_receiver: "📞",
  pager: "📟",
  fax: "📠",
  bulb: "💡",
  flashlight: "🔦",
  battery: "🔋",
  electric_plug: "🔌",
  mag: "🔍",
  mag_right: "🔎",
  lock: "🔒",
  unlock: "🔓",
  key: "🔑",
  bell: "🔔",
  bookmark: "🔖",
  link: "🔗",
  email: "📧",
  envelope: "✉️",
  mailbox: "📫",
  package: "📦",
  memo: "📝",
  pencil: "✏️",
  pencil2: "✏️",
  scissors: "✂️",
  clipboard: "📋",
  books: "📚",
  book: "📖",
  notebook: "📓",
  calendar: "📅",
  file_folder: "📁",
  chart: "📊",
  chart_with_upwards_trend: "📈",
  chart_with_downwards_trend: "📉",
  pushpin: "📌",
  paperclip: "📎",
  wrench: "🔧",
  hammer: "🔨",
  nut_and_bolt: "🔩",
  gear: "⚙️",
  // Symbols
  warning: "⚠️",
  construction: "🚧",
  rotating_light: "🚨",
  triangular_flag_on_post: "🚩",
  no_entry: "⛔",
  no_entry_sign: "🚫",
  x: "❌",
  o: "⭕",
  bangbang: "‼️",
  interrobang: "⁉️",
  hundred: "💯",
  checkered_flag: "🏁",
  crossed_flags: "🎌",
  white_check_mark: "✅",
  ballot_box_with_check: "☑️",
  heavy_check_mark: "✔️",
  heavy_multiplication_x: "✖️",
  negative_squared_cross_mark: "❎",
  heavy_plus_sign: "➕",
  heavy_minus_sign: "➖",
  heavy_division_sign: "➗",
  arrow_right: "➡️",
  arrow_left: "⬅️",
  arrow_up: "⬆️",
  arrow_down: "⬇️",
  arrow_upper_right: "↗️",
  arrow_lower_right: "↘️",
  arrow_lower_left: "↙️",
  arrow_upper_left: "↖️",
  arrow_up_down: "↕️",
  left_right_arrow: "↔️",
  arrow_backward: "◀️",
  arrow_forward: "▶️",
  arrow_up_small: "🔼",
  arrow_down_small: "🔽",
  leftwards_arrow_with_hook: "↩️",
  arrow_right_hook: "↪️",
  information_source: "ℹ️",
  rewind: "⏪",
  fast_forward: "⏩",
  arrow_double_up: "⏫",
  arrow_double_down: "⏬",
  ok: "🆗",
  new: "🆕",
  up: "🆙",
  cool: "🆒",
  free: "🆓",
  ng: "🆖",
  signal_strength: "📶",
  cinema: "🎦",
  koko: "🈁",
  six_pointed_star: "🔯",
  beginner: "🔰",
  trident: "🔱",
  black_square_button: "🔲",
  white_square_button: "🔳",
  red_circle: "🔴",
  large_blue_circle: "🔵",
  large_orange_diamond: "🔶",
  large_blue_diamond: "🔷",
  small_orange_diamond: "🔸",
  small_blue_diamond: "🔹",
  small_red_triangle: "🔺",
  small_red_triangle_down: "🔻",
  arrow_heading_up: "⤴️",
  arrow_heading_down: "⤵️",
  copyright: "©️",
  registered: "®️",
  tm: "™️",
  recycle: "♻️",
  wheelchair: "♿",
  anchor: "⚓",
  heart_decoration: "💟",
};

/**
 * Process text and replace emoji shortcodes with actual emojis
 * Supports :emoji_name: syntax
 */
export function processEmojis(text: string): string {
  return text.replace(/:([a-zA-Z0-9_+-]+):/g, (match, code) => {
    const emoji = emojiMap[code.toLowerCase()];
    return emoji || match;
  });
}

/**
 * Get emoji by shortcode
 */
export function getEmoji(code: string): string | undefined {
  return emojiMap[code.toLowerCase()];
}

/**
 * Search emojis by partial name
 */
export function searchEmojis(
  query: string,
  limit: number = 10
): Array<{ code: string; emoji: string }> {
  const lowerQuery = query.toLowerCase();
  const results: Array<{ code: string; emoji: string }> = [];

  for (const [code, emoji] of Object.entries(emojiMap)) {
    if (code.includes(lowerQuery)) {
      results.push({ code, emoji });
      if (results.length >= limit) break;
    }
  }

  return results;
}
