/**
 * AI Core Module - Core AI services and state management
 *
 * This module provides:
 * - AI service for text generation, tool calling, and media generation
 * - AI chat state management (Zustand store)
 * - AI provider management
 * - MCP (Model Context Protocol) client
 */

// AI Service
export {
  chatStream,
  chat,
  createPDFTools,
  getPDFTools,
  validateAPIKey,
  validateBuiltInAPIKey,
  testConnection,
  generateImage,
  generateSpeech,
  transcribeAudio,
  ToolParamSchemas,
  toolHandlers,
  type SimpleToolInvocation,
  type Message,
  type AIServiceConfig,
  type ChatOptions,
  type StreamResult,
  type SuggestAnnotationParams,
  type PendingAnnotationSuggestion,
  type CreatePlanParams,
  type UpdatePlanStepParams,
  type ImageGenerationConfig,
  type ImageGenerationOptions,
  type GeneratedImage,
  type ImageGenerationResult,
  type SpeechGenerationConfig,
  type SpeechGenerationOptions,
  type SpeechGenerationResult,
  type TranscriptionConfig,
  type TranscriptionOptions,
  type TranscriptionResult,
  isValidAudioFile,
  readAudioFile,
  createAudioBlobUrl,
} from "./ai-service";

// AI Chat Store
export {
  useAIChatStore,
  AI_MODELS,
  PRESET_PROVIDERS,
  TEMPLATE_VARIABLES,
  BUILTIN_QUICK_COMMANDS,
  BUILTIN_PROMPT_TEMPLATES,
  SYSTEM_PROMPT_PRESETS,
  type Message as ChatMessage,
  type TokenUsage,
  type SessionUsage,
  type BuiltInProvider,
  type AIProvider,
  type AIModel,
  type CustomProvider,
  type CustomAIModel,
  type Conversation,
  type PDFPageImage,
  type PDFContext,
  type ImageGenerationSettings,
  type SpeechSettings,
  type TranscriptionSettings,
  type QuickCommand,
  type PromptTemplate,
  type SystemPromptPreset,
  type AISettings,
  type ResearchStepType,
  type ResearchStepStatus,
  type ResearchStep,
  type ResearchSource,
  type ResearchWorkflowStatus,
  type ResearchWorkflow,
} from "./ai-chat-store";

// AI Providers
export {
  getOpenAIProvider,
  getAnthropicProvider,
  createCustomProvider,
  getLanguageModel,
  createAIProviderRegistry,
  clearProviderCache,
  getModelCapabilities,
  validateAPIKeyFormat,
  getImageModel,
  getSpeechModel,
  getTranscriptionModel,
  supportsImageGeneration,
  supportsSpeechGeneration,
  supportsTranscription,
  IMAGE_MODELS,
  IMAGE_SIZES,
  SPEECH_MODELS,
  SPEECH_VOICES,
  TRANSCRIPTION_MODELS,
  SUPPORTED_AUDIO_FORMATS,
  type ModelCapabilities,
  type ImageModelId,
  type ImageSize,
  type ImageQuality,
  type SpeechModelId,
  type SpeechVoice,
  type SpeechOutputFormat,
  type TranscriptionModelId,
  type AudioFormat,
} from "./ai-providers";

// MCP Client
export {
  createHTTPMCPClient,
  createSSEMCPClient,
  createStdioMCPClient,
  createMCPClientFromConfig,
  getMCPClient,
  getMCPTools,
  getAllMCPTools,
  closeMCPClient,
  closeAllMCPClients,
  listMCPResources,
  readMCPResource,
  listMCPPrompts,
  getMCPPrompt,
  isMCPAvailable,
  getMCPConnectionStatus,
  getMCPConnectionError,
  getCachedMCPTools,
  testMCPConnection,
  clearMCPConnectionStatus,
  isStdioMCPAvailable,
  MCP_SERVER_PRESETS,
  createMCPServerFromPreset,
  createCustomMCPServer,
  type MCPServerConfig,
  type MCPClient,
  type MCPConnectionStatus,
} from "./mcp-client";
